<?xml version="1.0" encoding="utf-8"?><Database Name="HotelDB" Class="HotelDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=laptop-a88v89ut;Initial Catalog=HotelDB;Integrated Security=True;Pooling=False;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HotelDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkerNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MoneyPaid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>